// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RobRSVD1_cpp
List RobRSVD1_cpp(const arma::mat& data, double sinit, const arma::vec& uinit, const arma::vec& vinit, double huberk, int niter, double tol);
RcppExport SEXP _rajiveplus_RobRSVD1_cpp(SEXP dataSEXP, SEXP sinitSEXP, SEXP uinitSEXP, SEXP vinitSEXP, SEXP huberkSEXP, SEXP niterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type sinit(sinitSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type uinit(uinitSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vinit(vinitSEXP);
    Rcpp::traits::input_parameter< double >::type huberk(huberkSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(RobRSVD1_cpp(data, sinit, uinit, vinit, huberk, niter, tol));
    return rcpp_result_gen;
END_RCPP
}
// RobRSVD_all_cpp
List RobRSVD_all_cpp(const arma::mat& data, int nrank, double sinit1, const arma::vec& uinit1, const arma::vec& vinit1, double huberk, int niter, double tol);
RcppExport SEXP _rajiveplus_RobRSVD_all_cpp(SEXP dataSEXP, SEXP nrankSEXP, SEXP sinit1SEXP, SEXP uinit1SEXP, SEXP vinit1SEXP, SEXP huberkSEXP, SEXP niterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nrank(nrankSEXP);
    Rcpp::traits::input_parameter< double >::type sinit1(sinit1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type uinit1(uinit1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vinit1(vinit1SEXP);
    Rcpp::traits::input_parameter< double >::type huberk(huberkSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(RobRSVD_all_cpp(data, nrank, sinit1, uinit1, vinit1, huberk, niter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rajiveplus_RobRSVD1_cpp", (DL_FUNC) &_rajiveplus_RobRSVD1_cpp, 7},
    {"_rajiveplus_RobRSVD_all_cpp", (DL_FUNC) &_rajiveplus_RobRSVD_all_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_rajiveplus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
